apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bk4l8ty2l-java-quarkus
  janus-idp.io/tekton: bk4l8ty2l-java-quarkus
  backstage.io/kubernetes-id: bk4l8ty2l-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bk4l8ty2l-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
