apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bk4l8ty2l-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c8bb83ed44.n9s3.p3.openshiftapps.com/rhtap/rhtap-qe:3351318dede843fb456e02fbf7a5c0dd38a6cadb@sha256:70377f6a07a11d2fadea1d9f0d1debcfece31c340c22d3fe8eefb5daffe67e15
          name: container-image
